#!/bin/bash

function make-yaml
{
# if {repo} is used for a repo to auto inject then the following
# formula might be inserted for a sed replacement
#        -e "s,\{repo\}(.*),${k8stestrepo}\\1,g"
    sed -r                                                                                                      \
        -e "s,namespace:.*k8s-jump.*,namespace: ${prefix}-k8s-jump,g"                                           \
        -e "s,app:.*k8s-jump.*,app: ${prefix}-k8s-jump,g"                                                       \
        -e "s,name:.*k8s-jump.*,name: ${prefix}-k8s-jump,g"                                                     \
        -e "s,authorized-keys:.*,authorized-keys: $(base64 -w 0 ~/.ssh/id_${ssh_key_type}.pub),g"               \
        -e "s,id-:.*,id-${ssh_key_type}: $(base64 -w 0 ~/.ssh/id_${ssh_key_type}),g"                            \
        -e "s,id-.pub:.*,id-${ssh_key_type}.pub: $(base64 -w 0 ~/.ssh/id_${ssh_key_type}.pub),g" ${inyaml}
}
